name: Publish to NuGet

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: 📦 Restore
        run: dotnet restore

      - name: 🛠️ Build
        run: dotnet build --no-restore --configuration Release

      - name: ✅ Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: 📦 Pack
        run: dotnet pack src/Orbital/Orbital.csproj --no-build --configuration Release --output ./nupkgs

      - name: 🧠 Determine version type
        id: version
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "tag=$tag" >> $GITHUB_OUTPUT
          if [[ "$tag" == *-* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: 🚀 Publish to NuGet (stable)
        if: steps.version.outputs.is_prerelease == 'false'
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: 🚧 Publish to GitHub Packages (pre-release)
        if: steps.version.outputs.is_prerelease == 'true'
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
